# Generated by Django 4.2.29 on 2026-03-05 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('assunto', models.CharField(blank=True, choices=[('critica', 'Crítica'), ('sugestao', 'Sugestão'), ('duvida', 'Dúvida'), ('erro', 'Erro'), ('outros', 'Outros')], max_length=20, null=True, verbose_name='Assunto')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula')),
                ('concorda_termos', models.BooleanField(default=False, verbose_name='Concorda com os termos')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do indicado')),
                ('nome_curso', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Curso')),
                ('nome_departamento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Departamento')),
                ('nome_funcao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Função')),
                ('nome_setor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Setor')),
                ('nome_empresa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Empresa')),
                ('nome_ou_ocupacao_atual', models.CharField(blank=True, max_length=200, null=True, verbose_name='Função/Ocupação Atual')),
                ('data_voto', models.DateTimeField(auto_now_add=True)),
                ('confirmacao', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesouros_do_ifpi.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesouros_do_ifpi.usuario')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
            },
        ),
    ]
