# Generated by Django 4.2.29 on 2026-03-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouros_do_ifpi', '0002_alter_categoria_id_alter_contato_id_alter_usuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_aceite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aceite'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ip_aceite',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Aceite'),
        ),
    ]
