# Generated by Django 4.2.29 on 2026-03-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouros_do_ifpi', '0003_usuario_data_aceite_usuario_ip_aceite'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='data_confirmacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together={('usuario', 'categoria')},
        ),
    ]
