# Generated by Django 4.2.29 on 2026-03-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouros_do_ifpi', '0004_voto_data_confirmacao_alter_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
